# Settings.yml
---
conf.py:
  project: TCA Reference
  copyright: 2000-2015
  version: 7
  release: 7
  intersphinx_mapping:
    t3inside:
    - https://docs.typo3.org/typo3cms/InsideTypo3Reference/
    - null
    t3api:
    - https://docs.typo3.org/typo3cms/CoreApiReference
    - null
    t3fal:
    - https://docs.typo3.org/typo3cms/FileAbstractionLayerReference/
    - null
    t3tsconfig:
    - https://docs.typo3.org/typo3cms/TSconfigReference
    - null
  html_theme_options:
    github_repository: TYPO3-Documentation/TYPO3CMS-Reference-TCA
    github_branch: latest
  latex_documents:
  - - Index
    - t3tca.tex
    - TCA Reference
    - Documentation Team
    - manual

  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
...
